# 十字交叉线配置参数
config:
  crosshair:
    strokeWidth: 40
    circle:
      r: 100 # 十字中心圆半径
      fill: transparent
      stroke: rgb(244, 70, 70)
    verticalLine:
      stroke: "#FF00FF"
    horizontalLine:
      stroke: "#00FF00"
  measure:
    fill: "#00FF00"
    activeFill: "#d80d18"
    initFill: "#fff"
    circle:
      r: 10
    line:
      strokeWidth: 4
